---
title: "CV"
author: "Benjamin D. Peterson, Ph.D."
date: "March 3, 2023"
output:
  pdf_document:
    latex_engine: pdflatex
    template: svm-latex-cv-modified.tex
  word_document: default
fontawesome: yes
fontfamily: mathpazo
fontsize: 11pt
geometry: margin=1in
jobtitle: Assistant Professor, University of Wisconsin - Milwaukee
linkcolor: blue
email: petersob@uwm.edu
phone: +1 410 980-4660
address: 600 E Greenfield Ave · 3017 GLRF building · Milwaukee, WI 53204
web: petersonlab.org
urlcolor: black
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Education

**University of Wisconsin - Madison** \hfill Madison, WI  
Ph.D. in Environmental Chemistry and Technology Program  \hfill August 2021  
Department of Civil and Environmental Engineering   
Thesis: "Ecophysiology of mercury-methylating organisms in freshwater ecosystems"   


**State University of New York at Geneseo** \hfill Geneseo, NY  
Bachelor of Science, *summa cum laude* Biochemistry \hfill May 2012  
Honors Minor (Edgar Fellows Honors Program)

-----

# Employment and Research Experience

**Assistant Professor** \hfill August 2024 - current  
University of Wisconsin - Milwaukee   
School of Freshwater Science    

**Postdoctoral Scholar** \hfill June 2022 - August 2024  
University of California - Davis \hfill PI: Dr. Brett Poulin  
Department of Environmental Toxicology    

**Postdoctoral Research Assistant** \hfill August 2021 - May 2022  
University of Wisconsin - Madison \hfill PI: Dr. Katherine McMahon  
Department of Bacteriology

**Graduate Research Assistant** \hfill September 2015 - August 2021  
University of Wisconsin - Madison \hfill PI: Dr. Katherine McMahon  
Departments of Bacteriology and Civil & Environmental Engineering   

**Research Fellow, Animal Biologist Contractor** \hfill 2012-2015  
National Institute on Aging: Neuroplasticity and Behavior Unit \hfill PI: Dr. Henriette van Praag  

**Undergraduate Research Assistant**: SUNY-Geneseo \hfill 2009-2012  

**Summer Undergraduate Research Assistant**: University of Buffalo \hfill Summer 2011  


---

# Major Grants and Funding

**Discovery and Innovation Grant - University of Wisconsin - Milwaukee** \hfill 2024-2026  
*Microbial physiology of mercury methylation*  
Role: Principal Investigator  
Funded amount: $49,925  

**DOE Joint Genome Institute New Investigator Community Science Project** \hfill 2023-current 
*Influence of labile permafrost dissolved organic matter on mercury-methylating organisms*  
Role: Principle Investigator  

**Roland L. Girolami Fellowship Award - UW-Madison Dept. of Bacteriology** \hfill 2020-2021  
Funding covered 1 year of graduate stipend (\$34,000) and $2000 for research expenses.  

**National Science Foundation Standard Grant - CBET** \hfill 2020-2023  
*Unrecognized microbial sources of methyl mercury in freshwater lakes*  
Role: Key Personnel, wrote first draft, co-editing with PI McMahon  
Funded amount: $329,608

**NIWR/USGS National Competitive Grant Program** \hfill 2019-2022  
*Microbial drivers of mercury methylation in freshwater eutrophic systems*  
Role: Key Personnel, wrote first draft, co-editing with PI McMahon  
Funded amount: $221,160  

**National Science Foundation Graduate Research Fellowship Program** \hfill 2016-2021  

---

# Publications

\* indicates co-first authorship  
\*\* indicates undergraduate student mentee

## Peer-reviewed

1. **Peterson, B.D.**, and Poulin, B.A. “Illuminating the black box: Trace element biogeochemistry from a microbial perspective.” Environmental Science & Technology 59, no. 42 (2025): 22373–85. https://doi.org/10.1021/acs.est.5c06816.

1. Armstrong, G.J., Janssen, S.E., Lepak, R.F., Rosera, T.J., **Peterson, B.D.**, Cushing, S.T., Tate, M.T., Hurley, J.P. (2025) “Seasonal stratification drives bioaccumulation of pelagic mercury sources in eutrophic lakes.” *ACS EST Water*, acsestwater.5c00028. https://doi.org/10.1021/acsestwater.5c00028.

1. **Peterson, B.D.**, Janssen, S.E., Poulin, B.A., Ogorek, J.M., White, A.M., McDaniel, E.A., Marick, R.A, Armstrong, G.J., Scheel, N.D., Tate, M.T., Krabbenhoft, D.P., McMahon, K.D. (2025). “Sulfate reduction drives elevated methylmercury formation in the water column of a eutrophic freshwater lake.” *Environmental Science & Technology*,  **59**(13), 6799-6811. https://doi.org/10.1021/acs.est.4c12759.

1. Krause, V.M., Baldwin, A.K., **Peterson, B.D.**, Krabbenhoft, D.P., Janssen, S.E., Willacker, J.J., Eagles-Smith, C.A., Poulin, B.A. (2024). "Riparian methylmercury production increases riverine mercury flux and food web concentrations." *Environmental Science & Technology*, **58**(46), 20490–20501. https://doi.org/10.1021/acs.est.4c08585

1. Cook, B.A., **Peterson, B.D.**, Ogorek, J.M., Janssen, S.E., Poulin, B.A. (2024). "Simulated sea level rise in coastal peat soils stimulates mercury methylation." *ACS Earth and Space Chemistry*, **8**(9), 1784–1796. https://doi.org/10.1021/acsearthspacechem.4c00124

1. **Peterson, B.D.**,  Poulin, B.A., Krabbenhoft, D.K., Tate, M.T., Baldwin, A.K., Naymik, J., Gastelecutto, N., McMahon, K.D. (2023). “Metabolically diverse microorganisms mediate methylmercury formation under nitrate-reducing conditions in a dynamic hydroelectric reservoir.” *The ISME Journal*, **17**, 1705–1718. https://doi.org/10.1038/s41396-023-01482-1

1. **Peterson, B.D.**, Krabbenhoft, D.K., McMahon, K.D., Ogorek, J.M., Tate, M.T., Orem, W.H., Poulin, B.A., (2023). “Environmental formation of methylmercury is controlled by synergy of inorganic mercury bioavailability and microbial mercury‐methylation capacity.” *Environmental Microbiology*, **25**(8) 1409-1423. https://doi.org/10.1111/1462-2920.16364.

1. Vivar, C., **Peterson, B.D.**, Pinto, A., Janke, E., and van Praag, H. (2023). “Running throughout middle-age keps old adult-born neurons wired.” *eNeuro* **10**(5) ENEURO.0084-23.2023. https://doi.org/10.1523/ENEURO.0084-23.2023.

1. Capo, E., **Peterson, B.D.**, Kim, M., Jones, D.S., Acinas, S.G., Amyot, M., Bertilsson, S., et al., (2023). “A consensus protocol for the recovery of mercury methylation genes from metagenomes.” *Molecular Ecology Resources* **23**(1), 190–204. https://doi.org/10.1111/1755-0998.13687.

1. Berg, S.M., **Peterson, B.D.**, McMahon, K.D., and Remucal, C.K., (2022). "Spatial and temporal variability of dissolved organic matter molecular composition in a stratified eutrophic lake." *Journal of Geophysical Research: Biogeosciences* **127**, e2021JG006550. https://doi.org/10.1029/2021JG006550.

1. Lepak, R.F., Tate, M.T., Ogorek, J.M., DeWild, J.F., **Peterson, B.D.**, Hurley, J.P., Krabbenhoft, D.P., (2020). "Aqueous elemental mercury production versus mercury inventories in the Lake Michigan airshed: Deciphering the spatial and diel controls of mercury gradients in air and water." *ACS ES&T Water* **1**, 719-727. https://doi.org/10.1021/acsestwater.0c00187.

1. **Peterson, B.D.**, McDaniel, E.A., \*\*Schmidt, A.G., Lepak, R.F., Janssen, S.E., Tran P.Q., \*\*Marick, R.A., Ogorek, J.M., DeWild, J.F., Krabbenhoft, D.P., McMahon, K.D. (2020). "Mercury methylation genes identified across diverse anaerobic microbial guilds in a eutrophic sulfate-enriched lake." *Environmental Science & Technology* **54**, 15840-15851. https://doi.org/10.1021/acs.est.0c05435.

1. McDaniel, E.A., **Peterson, B.D.**, Stevens, S.L.R., Tran, P.Q., Anantharaman, K., McMahon, K.D., (2020). "Expanded phylogenetic diversity and metabolic flexibility of mercury-methylating organisms". *mSystems* **5**(4), e00299-20.  https://doi.org/10.1128/mSystems.00299-20

1. Mohammad, H., Marchisella, F., Ortega-Martinez, S., Hollos, P., Eerola, K., Komulainen, E., Kulesskaya, N., Freemantle, E., Fagerholm, V., Savontous, E., Rauvala, H., **Peterson, B.D.**, van Praag, H., Coffey, E.T., (2018). "JNK1 controls adult hippocampal neurogenesis and imposes cell-autonomous control of anxiety behaviour from the neurogenic niche." *Molecular Psychiatry* 23, 362–374. https://doi.org/10.1038/mp.2016.203

1. Sah, N., **\*Peterson, B.D.**, Lubejko, S.T., Vivar, C., van Praag, H., (2017). "Running reorganizes the circuitry of one-week-old adult-born hippocampal neurons." *Scientific Reports* 7, 10903. https://doi.org/10.1038/s41598-017-11268-z

1. Vivar, C., **Peterson, B.D.**, van Praag, H., (2016). "Running rewires the neuronal network of adult-born dentate granule cells." *NeuroImage* 131, 29–41. https://doi.org/10.1016/j.neuroimage.2015.11.031

## Resources

1. Hg-cycling Microorganisms in Aquatic and Terrestrial Ecosystems (Hg-MATE) Database: Caitlin Gionfriddo, Eric Capo, **Benjamin D. Peterson**, Heyu Lin, Daniel Jones, Andrea G Bravo, Stefan Bertilsson, John Moreau, Katherine McMahon, Dwayne Elias, Cynthia Gilmour. Version 1. Posted January 29th, 2021

## Pre-prints

1. Tran, P.Q., Bachand, S.C., **Peterson, B.D.**, He, S., McMahon, K.D., Anantharaman, K. "Viral impacts on microbial activity and biogeochemical cycling in a seasonally anoxic freshwater lake." bioRxiv, posted April 19, 2023. https://doi.org/10.1101/2023.04.19.537559

1. White, A.M., Gonzalez Vazquez, A., McDaniel, E.A., **Peterson, B.D.**, Koch, P.L., Remucal, C.K., McMahon, K.D. "Expanded diversity of tfdA harboring bacteria across the natural and built environment." bioRxiv, posted September 30, 2022. https://doi.org/10.1101/2022.09.28.509959

1. \*\*Marick, R.A., **Peterson, B.D.**, McMahon, K.D. "Stratification in microbial communities with depth and redox status in a eutrophic lake across two years" bioRxiv, posted October 16, 2021. https://doi.org/10.1101/2021.10.15.464574

---

# Teaching and Mentoring

**Instructor of Record - University of Wisconsin - Milwaukee**

- Field Analysis and Experimentation in Freshwater Sciences \hfill Fall 2024, 2025

**Course contributor**

- Teaching Assistant (UC-Davis): Chemistry and Toxicology of Metals \hfill Two quarters
- Teaching Assistant (UC-Davis): CURE - The Arboretum: A Living Laboratory \hfill One quarter
- Teaching Assistant (UW-Madison): Environmental Microbiology \hfill Two semesters

**Undergraduate Mentor in Poulin Lab** \hfill 2022-2024
- **Emily Richter** - Investigating 


**Undergraduate Mentor in McMahon Lab** \hfill 2015-2020

- **Anna Schwendinger** - Assisting with routine mercury sampling. *Fall 2019 - Spring 2020*
- **Robert Marick** - Spatial and temporal dynamics of microbial communities along strong redox gradients in Lake Mendota. Preprint posted on bioRxiv. *Summer 2018 - Spring 2020*
- **Anna Grace Schmidt** - Zooplankton-associated microbiome in Lake Mendota. Lead undergrad for Microbial Observatory sampling. *Summer 2017 - Spring 2020*
    - UW–Madison College of Agricultural and Life Sciences Research Award \hfill 2018
    - ASM-Undergraduate Research Fellowship \hfill 2018
    - UW-Madison Sophomore Research Fellowship Award \hfill 2018
- **Diana Mendez** - Impact of zebra mussel feeding on planktonic microbial community *Summer, fall 2017*
- **Ariel Sorg** - Metagenomic characterization of methylotrophic freshwater Betaproteobacteria in Wisconsin, USA. *Summer 2017*
- **Mykala Sobieck** - Assisted with routine mercury sampling *Summer, fall 2016*
- **North Temperate Lakes Microbial Observatory Team** - Led team of 2-4 undergraduates per year in maintaining 20+ year time series. *2017-2019*


---

# Service

**ASLO Summer Conference**: Special Session Co-Chair \hfill 2024  
- Lead chair of "Mercury Biogeochemistry in a Changing World"  
**International Conference on Mercury as a Global Pollutant**: Special Session Co-Chair \hfill 2022  
- Co-chair of "Meta-omic and geochemical approaches to linking microbial activity to biogeochemical mercury cycling"  
**Mersorcium**: Organizing Board and Founding Member \hfill 2022-2024  
- Co-lead Seminar Committee, hosted monthly virtual seminar and workshops during semester  
**Ad hoc Journal Reviewer**: The ISME Journal, Environmental Science and Technology, ACS EST Water, Environmental Science and Pollution Research, Frontiers in Microbiology, Chemosphere, Environmental Research Letters, FACETS, Science of the Total Environment, Geosciences.  
**Water at UW Graduate Student Representative** \hfill 2018-2019  
**SETAC Young Environmental Scientist meeting**: Organizer \hfill 2018  
    - Organized 1-day science communication workshop  
**O.N. Allan Soil and Environmental Microbiology Small Grants Review Panelist** \hfill 2018  
**Postbac IRTA Representative**: National Institute on Aging \hfill 2013-2015  
**Geneseo Presidential Scholar**: SUNY-Geneseo \hfill 2011-2012  

---

# Other Grants, Scholarships, Awards, and Honors  

**NorCal SETAC Distinguished Early Career Scientist Award** \hfill 2023  
Becker Travel Award: $200-250 \hfill 2016, 2018, 2020  
Student Research Travel Grants - Conference: $1500 \hfill 2018  
Anna Grant Birge Memorial Scholarship: $1942 \hfill 2018  
Anna Grant Birge Memorial Scholarship: $1917 \hfill 2017  
Anna Grant Birge Memorial Scholarship: $2000 \hfill 2016  
Phi Beta Kappa \hfill 2012  
Ulmer-Jackson Biochemistry Award \hfill 2012  
**Goldwater Scholar**: $7500 \hfill 2011  
CRC Award to the Best Overall Student in Introductory Chemistry \hfill 2009  
Geneseo Dean’s List \hfill 7 semesters

---

# Presentations

## Invited presentations

1. Microbial insights into environmental methylmercury formation. **Environmental Engineering Sciences Seminar Series - Northwestern University McCormick School of Engineering**. Evanston, IL, United States. *January 2025*

1. Leveraging microbial communities to understand biogeochemical drivers of mercury methylation. **NorCal SETAC's 31st Annual Meeting**. Sacramento, CA, United States. *September 2023*


## Contributed oral presentations

1. Unraveling the complex role of sulfate reduction in environmental methylmercury formation. **Association for the Sciences of Limnology and Oceanography Summer Conference**. Madison, WI, United States. *June 2024*

1. Metabolically diverse microorganisms mediate methylmercury formation under nitrate-reducing conditions in a dynamic hydroelectric reservoir. **Hells Canyon Complex TMDL Advisory Committee Meeting**. Virtual meeting. *May 2024*

1. Linking microbial ecophysiology to environmental mercury methylation. **Applied and Environmental Microbiology Gordon Research Seminar**. South Hadley, MA, United States. *July 2023*

1. BONCAT applications for environmental biogeochemistry. **UC-Davis Environmental Biogeochemistry Symposium**. Davis, CA, United States. *July 2023*

1. Microbial and Biogeochemical Controls on Mercury Methylation in the Everglades. **Greater Everglades Ecosystem Restoration Conference**. Coral Springs, FL, United States. *April 2023*

1. Inorganic mercury bioavailability and microbial methylation capacity constraints on *in situ* mercury methylation. **International Conference on Mercury as a Global Pollutant**. Virtual conference. *July 2022*

1. Potential role of PVC microbes in mercury methylation in freshwater lakes. **Webinar on Planctomycetes, Verrucomicrobia, and Chlamydiae**. Virtual conference. *April 2021*

1. Identification of Mercury Methylating Organisms along a Trophic Gradient. **Greater Everglades Ecosystem Restoration Conference**. Virtual conference. *April 2021*

1. Identification of Mercury Methylating Organisms along a Trophic Gradient in the Florida Everglades. **International Symposium on the Biogeochemistry of Wetlands Conference**. Virtual conference. *March 2021*

1. Identification of Mercury Methylating Organisms along a Trophic Gradient. **Society for Environmental Toxicology and Chemistry**. Virtual conference. *November 2020*

1. Novel hgcA+ organisms dominate mercury-methylating community in water column of sulfate-enriched lake. **International Conference on Mercury as a Global Pollutant**. Krakow, Poland. *September 2019*

1. Mercury-methylating organisms in Lake Mendota. **American Water Resources Association Wisconsin Section Annual Meeting**. Delavan, WI, United States. *March 2019*


## Internal seminars

1. Microbial drivers of environmental mercury methylation in Lake Mendota, Wisconsin. **School of Freshwater Sciences Colloquium**, University of Wisconsin - Milwaukee. *November 2024*

1. Leveraging microbial ecology to understand the environmental cycling of mercury. **Department of Environmental Toxicology Seminar**, University of California - Davis. *June 1st, 2023*

1. Investigating the microbial influence on mercury methylation in the Florida Everglades. **Center for Limnology Weekly Seminar**, University of Wisconsin - Madison, virtual presentation. *April 2021*

1. Investigating the microbial influence on mercury methylation in the Florida Everglades. **Environmental Chemistry and Technology Weekly Seminar**, University of Wisconsin - Madison, virtual presentation. *February 2021*

1. Identification and activity of mercury-methylating microbes in Lake Mendota. **NTL-LTER Early Career Scientist Meeting**, University of Wisconsin - Madison, virtual presentation. *April 2020*

1. Identification and activity of mercury-methylating microbes in Lake Mendota. **Environmental Chemistry and Technology Seminar**, University of Wisconsin - Madison. *March 2020*

1. Mercury-methylating organisms in Lake Mendota. **Environmental Chemistry and Technology Seminar**, University of Wisconsin - Madison. *April 2019*

1. Mercury-methylating organisms in Lake Mendota. **Center for Limnology Weekly Seminar**. University of Wisconsin - Madison. *May 2019*

1. Distribution of mercury-methylating microbes along spatial and temporal redox gradients in a freshwater lake. **Environmental Chemistry and Technology Seminar**, University of Wisconsin - Madison. *April 2018*  

1. Meta-omics, microbes, and freshwater biogeochemistry! Oh My! **Environmental Chemistry and Technology Seminar**, University of Wisconsin - Madison. *April 2017*


## Poster presentations

1. From a black box to a window: Leveraging microbes to understand environmental mercury cycling. **Applied and Environmental Microbiology Gordon Research Conference**. South Hadley, MA. *July 2023*

1. Distribution of mercury-methylating microbes along spatial and temporal redox gradients in a freshwater lake. **International Society for Microbial Ecology Conference**. Leipzig, Germany. *August 2018*

1. Distribution of mercury-methylating microbes along spatial and temporal redox gradients in a freshwater lake. **SETAC Young Environmental Scientist Meeting**. University of Wisconsin - Madison. *March 2018*

1. Distribution of mercury-methylating microbes along spatial and temporal redox gradients in a freshwater lake. **International Conference on Mercury as a Global Pollutant**. Providence, RI. *July 2017*
 
1. Spatial distribution of ultramicrobacteria along Lake Erie. **IAGLR's Conference on Great Lakes Research**. Detroit, MI. *May 2017*

1. Vertical distribution of microbial communities during late stratification in a eutrophic, dimictic lake. **International Society for Microbial Ecology Conference**. Montreal, Canada *September 2016*

---

# Professional Development

Geochemist Workbench Virtual Workshop: “GWB Community Edition” \hfill February 2023  
DELTA Teaching in the College Classroom \hfill Spring 2019  
Anvi’o Workshop, University of Chicago \hfill April 2017  
Data Carpentry Workshop \hfill Fall 2016  
DELTA Research Mentorship Training  \hfill Summer 2016  
EDAMAME bioinformatics workshop \hfill Summer 2016  

---

# Society Memberships and Other Affiliations

Berkeley Lab Affiliate at Lawrence Berkeley National Laboratory \hfill 2023-current  
Association for the Sciences of Limnology and Oceanography \hfill 2020-2021, 2023-current  
International Society of Microbial Ecology \hfill 2018, 2023-current  
International Association for Great Lakes Research \hfill 2025-current  
